spring:
   profiles: 
      active: 
      - dev
---
server:
  port: 7001

spring:
   profiles: dev
   application: 
      name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称 注明:现在是在本机,且目前只要一个eureka
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己。
    fetch-registry: false #false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 单机defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务,都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001

spring:
   profiles: test
   application: 
      name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称 注明:现在是在本机,且目前只要一个eureka
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己。
    fetch-registry: false #false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 单机defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务,都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/